# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  controladorpedidos:
    image: controladorpedidos
    build:
      context: .
      dockerfile: src/Adapters/Driving/ControladorPedidos/Dockerfile
    ports:
      - 5003:5003
    environment:
      - ConnectionStrings__DefaultConnection=server=database_mysql;database=controlador_pedidos;user=root;password=P@ssWord
    depends_on:
      - database_mysql
    networks:
      - controladorpedidos-network

  database_mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssWord
      MYSQL_DATABASE: controlador_pedidos
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - controladorpedidos-network

networks:
  controladorpedidos-network:
    driver: bridge
volumes:
  mysql_data:
    driver: local