name: Build and Push Docker Image

on:
  push:
    branches: [kubernetes-files]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: CD
        run: cd src/ControladorPedidos.App

      - name: LS
        run: ls
      #- name: Docker Login
      #  run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      #- name: Docker Build
      #  run: docker build . -t ghcr.io/renansx/controladorpedidos-app:latest

      #- name: Docker Push
      #  run: docker push ghcr.io/renansx/controladorpedidos-app:latest
