name: Build and Push Docker Image

on:
  release:
    types:
      - published

permissions: write-all

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Docker Build
        run: docker build . -f src/ControladorPedidos.App/Dockerfile -t ghcr.io/renansx/controladorpedidos-app:latest -t ghcr.io/renansx/controladorpedidos-app:${{ github.event.release.tag_name }}

      - name: Docker Push
        run: |
          docker push ghcr.io/renansx/controladorpedidos-app:latest
          docker push ghcr.io/renansx/controladorpedidos-app:${{ github.event.release.tag_name }}
