name: Build and Push Docker Image

on:
  release:
    types:
      - published

permissions: write-all

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Docker Build Controlador Pedidos
        run: |
          docker build . -f src/ControladorPedidos.App/Dockerfile -t ghcr.io/tech-challenge-grupo-6/controladorpedidos-app:latest -t ghcr.io/tech-challenge-grupo-6/controladorpedidos-app:${{ github.event.release.tag_name }}

      - name: Docker Build Controlador Pagamento
        run: |
          docker build . -f src/ControladorPagamento.Fake/Dockerfile -t ghcr.io/tech-challenge-grupo-6/controladorpagamento-fake:latest -t ghcr.io/tech-challenge-grupo-6/controladorpagamento-fake:${{ github.event.release.tag_name }}

      - name: Docker Push
        run: |
          docker push ghcr.io/tech-challenge-grupo-6/controladorpedidos-app:latest
          docker push ghcr.io/tech-challenge-grupo-6/controladorpedidos-app:${{ github.event.release.tag_name }}
          docker push ghcr.io/tech-challenge-grupo-6/controladorpagamento-fake:latest
          docker push ghcr.io/tech-challenge-grupo-6/controladorpagamento-fake:${{ github.event.release.tag_name }}
